### ISSUE TITLE
No arrow sign in Sequence Diagram 

### ISSUE THREAD

**Issue by jibundit** [inkdropapp/inkdrop-mermaid#9]
Using a code of sequence diagram, Alice/Bob/John example, the preview doesn't show the arrow while graph LP works fine. Inkdrop version 5.4.1 (Demo).

<img width="490" alt="image" src="https://user-images.githubusercontent.com/7513862/175476980-429b811a-f47f-4cdd-b775-4c35c234dd7d.png">

**Comment by craftzdog** [comment]
It's been already fixed in the normal version.

**Comment by feddybear** [comment]
Hi @craftzdog Matsuyama-san, I'm using 5.5.3 (regular user here), but still get this bug (please see attached)

<img width="986" alt="image" src="https://user-images.githubusercontent.com/921006/224378458-39a3a0f0-0954-457e-9761-1597a2c866b9.png">

**Comment by feddybear** [comment]
> Hi @craftzdog Matsuyama-san, I'm using 5.5.3 (regular user here), but still get this bug (please see attached)
> 
> <img alt="image" width="986" src="https://user-images.githubusercontent.com/921006/224378458-39a3a0f0-0954-457e-9761-1597a2c866b9.png">

**[23-03-12 update]** nevermind, it's a mermaid syntax issue.  Correcting the `-->`'s on the example displayed (e.g. `->>` and `-->>`) in README.md will show the arrowheads

**Comment by craftzdog** [comment]
Thanks @feddybear, I've fixed the example.
